# Generated by Django 4.2.21 on 2025-07-15 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('group', models.CharField(blank=True, max_length=128, null=True)),
                ('teacher', models.CharField(blank=True, max_length=128, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('audio', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_duration', models.FloatField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('question_text', models.TextField(blank=True, default=None, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('correct_answers', models.JSONField(blank=True, default=list, null=True)),
                ('header', models.TextField(blank=True, default='', null=True)),
                ('instruction', models.TextField(blank=True, default='', null=True)),
                ('image', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('points', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.listeningpart')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_limit', models.PositiveIntegerField(default=60)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=10)),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WritingTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('band_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='in_progress', max_length=32)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('flagged', models.JSONField(blank=True, default=dict)),
                ('time_left', models.IntegerField(default=3600)),
                ('score', models.FloatField(blank=True, null=True)),
                ('correct_answers_count', models.IntegerField(default=0)),
                ('total_questions_count', models.IntegerField(default=0)),
                ('band_score', models.FloatField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.readingtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.IntegerField(default=0)),
                ('band_score', models.FloatField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.readingtestsession')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('group_number', models.CharField(blank=True, default='', max_length=32)),
                ('question_type', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('header', models.CharField(blank=True, default='', max_length=255)),
                ('instruction', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('question_text', models.TextField(blank=True, default=None, null=True)),
                ('points', models.FloatField(default=1)),
                ('correct_answers', models.JSONField(blank=True, default=list, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.readingpart')),
            ],
        ),
        migrations.AddField(
            model_name='readingpart',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.readingtest'),
        ),
        migrations.CreateModel(
            name='ReadingAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.readingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('timer_seconds', models.IntegerField(default=0)),
                ('audio_position', models.FloatField(default=0)),
                ('status', models.CharField(default='in_progress', max_length=32)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('submitted', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('flagged', models.JSONField(blank=True, default=dict)),
                ('time_left', models.IntegerField(default=1800)),
                ('score', models.FloatField(blank=True, null=True)),
                ('correct_answers_count', models.IntegerField(default=0)),
                ('total_questions_count', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listeningtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.IntegerField(default=0)),
                ('band_score', models.FloatField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.listeningtestsession')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTestClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloned_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clone_of', to='core.listeningtest')),
                ('source_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='core.listeningtest')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listeningquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.listeningtestsession')),
            ],
        ),
        migrations.AddField(
            model_name='listeningpart',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.listeningtest'),
        ),
        migrations.CreateModel(
            name='ListeningAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.listeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=10)),
                ('question_text', models.TextField()),
                ('submitted_text', models.TextField()),
                ('score_task', models.FloatField(null=True)),
                ('score_coherence', models.FloatField(null=True)),
                ('score_lexical', models.FloatField(null=True)),
                ('score_grammar', models.FloatField(null=True)),
                ('overall_band', models.FloatField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.writingprompt')),
                ('test_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.writingtestsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
