# Generated by Django 4.2.21 on 2025-06-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='listening_audio/')),
                ('audio_duration', models.FloatField(default=0)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=32)),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('correct_answers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.listeningpart')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTestClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.IntegerField(default=0)),
                ('band_score', models.FloatField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listeningansweroptionv2',
            name='question',
        ),
        migrations.RemoveField(
            model_name='listeningaudio',
            name='test',
        ),
        migrations.RemoveField(
            model_name='listeningquestionv2',
            name='section',
        ),
        migrations.RemoveField(
            model_name='listeningsection',
            name='test',
        ),
        migrations.AlterModelOptions(
            name='listeningtestsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='listeningtestsession',
            name='band_score',
        ),
        migrations.RemoveField(
            model_name='listeningtestsession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='listeningtestsession',
            name='raw_score',
        ),
        migrations.RemoveField(
            model_name='listeningtestsession',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='audio_position',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='status',
            field=models.CharField(default='in_progress', max_length=32),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='time_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='timer_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listeningtestsession',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ListeningAnswerKeyV2',
        ),
        migrations.DeleteModel(
            name='ListeningAnswerOptionV2',
        ),
        migrations.DeleteModel(
            name='ListeningAudio',
        ),
        migrations.DeleteModel(
            name='ListeningQuestionV2',
        ),
        migrations.DeleteModel(
            name='ListeningSection',
        ),
        migrations.AddField(
            model_name='listeningtestresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.listeningtestsession'),
        ),
        migrations.AddField(
            model_name='listeningtestclone',
            name='cloned_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clone_of', to='core.listeningtest'),
        ),
        migrations.AddField(
            model_name='listeningtestclone',
            name='source_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='core.listeningtest'),
        ),
        migrations.AddField(
            model_name='listeningstudentanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.listeningtestsession'),
        ),
        migrations.AddField(
            model_name='listeningpart',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.listeningtest'),
        ),
        migrations.AddField(
            model_name='listeningansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.listeningquestion'),
        ),
    ]
