# Generated by Django 4.2.21 on 2025-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingpart',
            old_name='image_url',
            new_name='passage_image_url',
        ),
        migrations.AddField(
            model_name='readingpart',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='readingpart',
            name='passage_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
