# Generated by Django 4.2.21 on 2025-07-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_image_url_readingpart_passage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingansweroption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readingansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='core.readingquestion'),
        ),
    ]
