# Generated by Django 4.2.21 on 2025-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listeningansweroption_listeningpart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtestsession',
            name='flagged',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='listeningtestsession',
            name='time_left',
            field=models.IntegerField(default=1800),
        ),
    ]
