# Generated by Django 4.2.21 on 2025-07-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_readingansweroption_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtestsession',
            name='current_part',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='readingtestsession',
            name='current_question',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
