# Generated by Django 4.2.21 on 2025-07-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_readingtestsession_current_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingtestsession',
            old_name='submitted',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='readingtestsession',
            old_name='completed_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='readingtestsession',
            old_name='started_at',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='readingtestsession',
            old_name='time_left',
            new_name='time_left_seconds',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='band_score',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='correct_answers_count',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='current_part',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='score',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='readingtestsession',
            name='total_questions_count',
        ),
        migrations.AddField(
            model_name='readingtestresult',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingtestresult',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='readingtestresult',
            name='raw_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='readingtestresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.readingtestsession'),
        ),
    ]
