# Generated by Django 4.2.21 on 2025-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='header',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
