# Generated by Django 4.2.21 on 2025-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_listeningquestion_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listening_images/'),
        ),
    ]
