# Generated by Django 4.2.21 on 2025-07-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_submitted_readingtestsession_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingpart',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='readingquestion',
            options={'ordering': ['order']},
        ),
    ]
