# Generated by Django 4.2.21 on 2025-07-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_group_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingquestion',
            name='group_number',
        ),
    ]
