# Generated by Django 4.2.21 on 2025-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listeningquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
