# Generated by Django 4.2.21 on 2025-07-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_listeningquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
