# Generated by Django 4.2.21 on 2025-07-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_group_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='header',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
