# Generated by Django 4.2.21 on 2025-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_listeningquestion_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
