# Generated by Django 4.2.21 on 2025-07-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_listeningquestion_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningansweroption',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='scoring_mode',
            field=models.CharField(choices=[('total', 'Total Points'), ('per_correct', 'Per Correct Answer')], default='total', max_length=20),
        ),
    ]
