# Generated by Django 4.2.21 on 2025-07-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_listeningansweroption_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeningquestion',
            options={'ordering': ['order']},
        ),
    ]
