# Generated by Django 4.2.21 on 2025-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_listeningquestion_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtestsession',
            name='correct_answers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='total_questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
