# Generated by Django 4.2.21 on 2025-08-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacher_feedback_and_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_coherence_score',
            field=models.FloatField(blank=True, help_text='Coherence & Cohesion (0-9)', null=True),
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_grammar_score',
            field=models.FloatField(blank=True, help_text='Grammatical Range & Accuracy (0-9)', null=True),
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_lexical_score',
            field=models.FloatField(blank=True, help_text='Lexical Resource (0-9)', null=True),
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_overall_score',
            field=models.FloatField(blank=True, help_text='Overall Band Score (0-9)', null=True),
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_task_score',
            field=models.FloatField(blank=True, help_text='Task Response/Achievement (0-9)', null=True),
        ),
    ]
