# Generated by Django 4.2.21 on 2025-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_email_user_first_name_user_group_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningpart',
            name='audio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
