# Generated by Django 4.2.21 on 2025-08-19 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teacherfeedback_teacher_coherence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_satisfied', models.BooleanField(help_text='Student satisfaction with teacher')),
                ('reason', models.TextField(blank=True, help_text='Reason if not satisfied', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'submitted_at')},
            },
        ),
    ]
