# Generated by Django 4.2.21 on 2025-07-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_listeningpart_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningquestion',
            name='order',
        ),
    ]
