# Generated by Django 4.2.21 on 2025-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teachersatisfactionsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('curator', 'Curator')], max_length=20),
        ),
    ]
