# Generated by Django 4.2.21 on 2025-07-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_listeningquestion_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='correct_answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='header',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='instruction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
