# Generated by Django 4.2.21 on 2025-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curator_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
