# Generated by Django 4.2.21 on 2025-08-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_curator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('part1', 'Part 1 - Introduction & Interview'), ('part2', 'Part 2 - Individual Long Turn'), ('part3', 'Part 3 - Two-Way Discussion')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('band_score', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speakingtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluency_coherence_score', models.FloatField(blank=True, help_text='Fluency & Coherence (0-9)', null=True)),
                ('lexical_resource_score', models.FloatField(blank=True, help_text='Lexical Resource (0-9)', null=True)),
                ('grammatical_range_accuracy_score', models.FloatField(blank=True, help_text='Grammatical Range & Accuracy (0-9)', null=True)),
                ('pronunciation_score', models.FloatField(blank=True, help_text='Pronunciation (0-9)', null=True)),
                ('overall_band_score', models.FloatField(blank=True, help_text='Overall Band Score (0-9)', null=True)),
                ('feedback_fluency_coherence', models.TextField(blank=True, default='')),
                ('feedback_lexical', models.TextField(blank=True, default='')),
                ('feedback_grammar', models.TextField(blank=True, default='')),
                ('feedback_pronunciation', models.TextField(blank=True, default='')),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedback', to='core.speakingassessment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_speaking_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='speakingassessment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speakingtest'),
        ),
        migrations.AddField(
            model_name='speakingassessment',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.speakingtestsession'),
        ),
        migrations.AddField(
            model_name='speakingassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
