# Generated by Django 4.2.21 on 2025-08-27 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_speakingassessment_speakingtest_speakingtestsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluency_coherence_score', models.FloatField(blank=True, help_text='Fluency and Coherence (0-9)', null=True)),
                ('lexical_resource_score', models.FloatField(blank=True, help_text='Lexical Resource (0-9)', null=True)),
                ('grammatical_range_score', models.FloatField(blank=True, help_text='Grammatical Range and Accuracy (0-9)', null=True)),
                ('pronunciation_score', models.FloatField(blank=True, help_text='Pronunciation (0-9)', null=True)),
                ('overall_band_score', models.FloatField(blank=True, help_text='Overall Band Score (calculated)', null=True)),
                ('fluency_coherence_feedback', models.TextField(blank=True, default='')),
                ('lexical_resource_feedback', models.TextField(blank=True, default='')),
                ('grammatical_range_feedback', models.TextField(blank=True, default='')),
                ('pronunciation_feedback', models.TextField(blank=True, default='')),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total session duration', null=True)),
                ('time_markers', models.JSONField(blank=True, default=list, help_text='Time markers with notes')),
                ('session_notes', models.TextField(blank=True, default='', help_text='Additional session notes')),
                ('completed', models.BooleanField(default=False, help_text='Session completed by teacher')),
                ('conducted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-conducted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='speakingteacherfeedback',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='speakingteacherfeedback',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='speakingtestsession',
            name='test',
        ),
        migrations.RemoveField(
            model_name='speakingtestsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpeakingAssessment',
        ),
        migrations.DeleteModel(
            name='SpeakingTeacherFeedback',
        ),
        migrations.DeleteModel(
            name='SpeakingTest',
        ),
        migrations.DeleteModel(
            name='SpeakingTestSession',
        ),
    ]
