# Generated by Django 4.2.21 on 2025-08-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_speakingsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfeedback',
            name='teacher_overall_score',
            field=models.FloatField(blank=True, help_text='Overall Band Score (calculated)', null=True),
        ),
    ]
