# Generated by Django 4.2.21 on 2025-08-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_teacherfeedback_teacher_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_coherence_feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback for Coherence & Cohesion'),
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_grammar_feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback for Grammatical Range & Accuracy'),
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_lexical_feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback for Lexical Resource'),
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher_task_feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback for Task Response/Achievement'),
        ),
    ]
