# Generated by Django 4.2.21 on 2025-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teacherfeedback_teacher_coherence_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningtestsession',
            name='time_left',
            field=models.IntegerField(default=2400),
        ),
    ]
