# Generated by Django 4.2.21 on 2025-08-30 12:00

from django.db import migrations


def update_existing_sessions_time_left(apps, schema_editor):
    """Update existing ListeningTestSession records from 1800 to 2400 seconds"""
    ListeningTestSession = apps.get_model('core', 'ListeningTestSession')
    
    # Update all existing sessions that still have 1800 seconds
    updated_count = ListeningTestSession.objects.filter(time_left=1800).update(time_left=2400)
    
    print(f"Updated {updated_count} ListeningTestSession records from 1800 to 2400 seconds")


def reverse_update_existing_sessions_time_left(apps, schema_editor):
    """Reverse: Update existing ListeningTestSession records from 2400 to 1800 seconds"""
    ListeningTestSession = apps.get_model('core', 'ListeningTestSession')
    
    # Update all existing sessions that have 2400 seconds back to 1800
    updated_count = ListeningTestSession.objects.filter(time_left=2400).update(time_left=1800)
    
    print(f"Reversed: Updated {updated_count} ListeningTestSession records from 2400 to 1800 seconds")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_listeningtestsession_time_left'),
    ]

    operations = [
        migrations.RunPython(
            update_existing_sessions_time_left,
            reverse_update_existing_sessions_time_left
        ),
    ]

