# Generated by Django 4.2.21 on 2025-09-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_writingtest_writingtask_essay_writing_task_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writingtask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='essay',
            name='teacher_feedback_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='writing_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.writingtask'),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='writingtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='writingtest',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='writingtest',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
