# Generated by Django 4.2.21 on 2025-09-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_writingtask_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='teacher_feedback_published',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='writing_task',
        ),
        migrations.RemoveField(
            model_name='writingtestsession',
            name='test',
        ),
        migrations.DeleteModel(
            name='WritingTask',
        ),
        migrations.DeleteModel(
            name='WritingTest',
        ),
    ]
