# Generated by Django 4.2.21 on 2025-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_writingtest_writingtask_essay_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='explanation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='explanation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='explanation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
