# Generated by Django 5.1.3 on 2025-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_listeningtest_explanation_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpart',
            name='passage_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
