# Generated by Django 5.1.3 on 2025-10-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_passage_heading_to_reading_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='is_diagnostic_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningtestsession',
            name='is_diagnostic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='is_diagnostic_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingtestsession',
            name='is_diagnostic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='is_diagnostic_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingtestsession',
            name='is_diagnostic',
            field=models.BooleanField(default=False),
        ),
    ]
