# Generated by Django 5.1.3 on 2025-10-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_listeningtest_is_diagnostic_template_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_user DROP COLUMN IF EXISTS is_sales_user;",
            reverse_sql="ALTER TABLE core_user ADD COLUMN is_sales_user BOOLEAN DEFAULT FALSE;"
        ),
    ]
