# Generated by Django 4.2.21 on 2025-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20251004_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='listening/questions/'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='reading/questions/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('speaking_mentor', 'Speaking Mentor'), ('admin', 'Admin'), ('curator', 'Curator')], max_length=20),
        ),
    ]
