# Generated by Django 4.2.21 on 2025-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_listeningansweroption_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='task_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='task_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
