# Generated by Django on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_fix_placement_test_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementtestsubmission',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]

