# Generated by Django 4.2.21 on 2026-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_fix_placement_test_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementtestsubmission',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('speaking_mentor', 'Speaking Mentor'), ('admin', 'Admin'), ('curator', 'Curator'), ('placement_viewer', 'Placement Viewer')], max_length=20),
        ),
    ]
