# Generated by Django 4.2.21 on 2026-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_placementtestsubmission_grade_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementtestsubmission',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]

